### ISSUE TITLE
Manual da api...

### ISSUE THREAD

**Issue by amadeujunior18** [murilosandiego/node-sicredi#1]
Ola Murilo tudo bem mano preciso fazer uma api em php para consumir esse ws, mais não encontro o manual dela em lugar nenhum, vc teria ainda ele?

**Comment by murilosandiego** [comment]
Blz Amadeu. Tenho aqui sim. Vou colocar ela no readme.

**Comment by amadeujunior18** [comment]
Agradeço a ajuda.

**Comment by murilosandiego** [comment]
Cara, desculpa a demora. Segue link do manual [https://github.com/murilosandiego/node-sicredi/blob/master/docs/manualECommAPISicredi.pdf](https://github.com/murilosandiego/node-sicredi/blob/master/docs/manualECommAPISicredi.pdf)
