### ISSUE TITLE
Ajuda com o campo Posto

### ISSUE THREAD

**Issue by lucas-freitas00** [murilosandiego/node-sicredi#2]
Estou tentando fazer a implementação desta **API** para um determinado cliente, já geramos a chave master a a chave **auth** que é valida por **24hrs**. Porém sempre que tento utilizar o método find() tanto com intervalo de data ou algum 'nosso numero', sempre recebo o erro **E0024**. Gostaria de saber o porque desse erro e como corrigi-lo?

**Comment by murilosandiego** [comment]
Boa noite, Lucas. Tudo bem? Além do código de erro aparece alguma mensagem?

**Comment by lucas-freitas00** [comment]
Olá boa tarde, depois de uma boa pesquisa e um contato diretamente com o suporte do meu cliente consegui achar o posto. Porém tive que reescrever o projeto em PHP, para poder usar no sistema de empresa, que é web e é desenvolvido em PHP. Consegui desenvolver quase todas as funcionalidade, Somente a funcionalidade de ALTERAR um titulo já registrado, não consegui refaze-la, pois não encontrei nenhuma referencia na documentação postada na pasta docs, e não compreendi totalmente a lógica feita em node. Gostaria de saber quais são os atributos obrigatórios para fazer essa alteração. Gostaria de saber também sobre outras questões como impressão de boleto, pois no método atual (remessa e retorno), há um campo onde informo se a impressão e distribuição dos boletos é feita pelo banco ou pelo cliente. Caso possível gostaria de entrar em contato para esclarecer essas dúvidas, meu e-mail para contato é lucasfreitas.alves00@gmail.com.

**Comment by murilosandiego** [comment]
Boa noite, Lucas. Me envia um e-mail (murilosandiego1@gmail.com) que podemos trocar uma ideia.

**Comment by murilosandiego** [comment]
Lucas, bom dia. 
Acabei de verificar e realmente estava faltando a parte da alteração no manual. Subi uma nova versão com este item. 

Em relação a alteração os campos obrigatórios são: Agência, Posto, Código do beneficiário, Nosso número do título e o comando de instrução (PEDIDO BAIXA, CONCESSAO ABATIMENTO, ALTERACAO VENCIMENTO etc). Verifique o item 6 do manual para mais informações. 

Em relação a impressão do boleto o banco é responsável pela geração, então não precisa se preocupar com todas aquelas informações que são necessárias para a geração do arquivo de remessa. 

Ao emitir um boleto o banco já devolve o nosso número e através dele já é possível imprimir, consultar situação etc.
